version: '2.0'

services:
  web:
    build: ./src
    command: uvicorn main:app --reload --workers 1 --host 0.0.0.0 --port 8000
    volumes:
      - ./src/:/usr/src/
    ports:
      - 8002:8000
